[package]
name = "tensorflow"
version = "0.0.3"
authors = ["Adam Crume <acrume@google.com>"]
description = "Rust language bindings for TensorFlow."
license = "Apache-2.0"
keywords = ["TensorFlow", "bindings"]
readme = "README.md"
repository = "https://github.com/google/tensorflow-rust"

[dependencies]
libc = "0.2"
tensorflow-sys = { version = "0.4", path = "tensorflow-sys" }

[dev-dependencies]
random = "0.12"

[features]
tensorflow_unstable = []

[workspace]
