[package]
name = "tensorflow"
version = "0.0.2"
authors = ["Adam Crume <acrume@google.com>"]
description = "Rust language bindings for TensorFlow.  This project is still under active development and not yet ready for widespread use."
license = "Apache-2.0"
keywords = ["TensorFlow", "bindings"]
readme = "README.md"
repository = "https://github.com/google/tensorflow-rust"

[dependencies]
libc = "^0.2"
libtensorflow-sys = { version = "0.0.1", path = "libtensorflow-sys" }

[features]
default = []
tensorflow_unstable = []
