[package]
name = "tensorflow"
version = "0.3.0"
authors = ["Adam Crume <acrume@google.com>"]
description = "Rust language bindings for TensorFlow."
license = "Apache-2.0"
keywords = ["TensorFlow", "bindings"]
readme = "README.md"
repository = "https://github.com/tensorflow/rust"
documentation = "https://tensorflow.github.io/rust/tensorflow"

[dependencies]
libc = "0.2"
num-complex = { version = "0.1.35", default-features = false }
tensorflow-sys = { version = "0.7.0", path = "tensorflow-sys" }

[dev-dependencies]
random = "0.12"

[features]
tensorflow_unstable = []

[workspace]
