[package]
name = "tensorflow"
version = "0.1.0"
authors = ["Adam Crume <acrume@google.com>"]
description = "Rust language bindings for TensorFlow.  This project is still under active development and not yet ready for widespread use."
license = "Apache-2.0"
keywords = ["TensorFlow", "bindings"]
readme = "README.md"
repository = "https://github.com/google/tensorflow-rust"

[dependencies]
libc = "0.1"
libtensorflow-sys = { path = "libtensorflow-sys" }
