[package]
name = "tensorflow-sys"
version = "0.5.0"
license = "Apache-2.0"
authors = [
  "Adam Crume <acrume@google.com>",
  "Ivan Ukhov <ivan.ukhov@gmail.com>",
]
description = "The package provides bindings to TensorFlow."
documentation = "https://google.github.io/tensorflow-rust"
homepage = "https://github.com/google/tensorflow-rust"
repository = "https://github.com/google/tensorflow-rust"
build = "build.rs"
links = "tensorflow"

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3"
